# Generated by Django 2.0.7 on 2018-07-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jav', '0003_auto_20180709_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='date',
            field=models.DateTimeField(blank=True, verbose_name='Update date'),
        ),
    ]
