# Generated by Django 2.0.7 on 2018-07-10 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jav', '0004_auto_20180710_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='actress',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
