# Generated by Django 2.0.7 on 2018-07-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jav', '0005_actress_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='actress',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='actress',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
